// Source: generated by https://github.com/Microsoft/CodeContracts

using System.Reflection;
using System.Runtime.CompilerServices;

namespace System.Diagnostics.Contracts
{
    internal static class __ContractsRuntime
    {
        [ThreadStatic]
        internal static int insideContractEvaluation;

        [DebuggerNonUserCode]
        internal static void ReportFailure(ContractFailureKind kind, string msg, string conditionTxt, Exception inner)
        {
            string text = ContractHelper.RaiseContractFailedEvent(kind, msg, conditionTxt, inner);
            if (text != null)
            {
                ContractHelper.TriggerFailure(kind, text, msg, conditionTxt, inner);
            }
        }

        [DebuggerNonUserCode]
        internal static void Invariant(bool condition, string msg, string conditionTxt)
        {
            if (!condition)
            {
                __ContractsRuntime.ReportFailure(ContractFailureKind.Invariant, msg, conditionTxt, null);
            }
        }

        [DebuggerNonUserCode]
        internal static void Assert(bool condition, string msg, string conditionTxt)
        {
            if (!condition)
            {
                __ContractsRuntime.ReportFailure(ContractFailureKind.Assert, msg, conditionTxt, null);
            }
        }

        [DebuggerNonUserCode]
        internal static void Assume(bool condition, string msg, string conditionTxt)
        {
            if (!condition)
            {
                __ContractsRuntime.ReportFailure(ContractFailureKind.Assume, msg, conditionTxt, null);
            }
        }

        [DebuggerNonUserCode]
        internal static void Requires(bool condition, string msg, string conditionTxt)
        {
            if (!condition)
            {
                __ContractsRuntime.ReportFailure(ContractFailureKind.Precondition, msg, conditionTxt, null);
            }
        }

        [DebuggerNonUserCode]
        internal static void Requires<TException>(bool condition, string msg, string conditionTxt) where TException : Exception
        {
            if (condition)
            {
                return;
            }
            string text = ContractHelper.RaiseContractFailedEvent(ContractFailureKind.Precondition, msg, conditionTxt, null);
            Exception ex = null;
            ConstructorInfo constructor = typeof(TException).GetConstructor(new Type[]
            {
                typeof(string),
                typeof(string)
            });
            if (constructor != null)
            {
                if (constructor.GetParameters()[0].Name == "paramName")
                {
                    ex = (constructor.Invoke(new object[]
                    {
                        msg,
                        text
                    }) as Exception);
                }
                else
                {
                    ex = (constructor.Invoke(new object[]
                    {
                        text,
                        msg
                    }) as Exception);
                }
            }
            else
            {
                constructor = typeof(TException).GetConstructor(new Type[]
                {
                    typeof(string)
                });
                if (constructor != null)
                {
                    ex = (constructor.Invoke(new object[]
                    {
                        text
                    }) as Exception);
                }
            }
            if (ex == null)
            {
                throw new ArgumentException(text, msg);
            }
            throw ex;
        }

        [DebuggerNonUserCode]
        internal static void Ensures(bool condition, string msg, string conditionTxt)
        {
            if (!condition)
            {
                __ContractsRuntime.ReportFailure(ContractFailureKind.Postcondition, msg, conditionTxt, null);
            }
        }

        [DebuggerNonUserCode]
        internal static void EnsuresOnThrow(bool condition, string msg, string conditionTxt, Exception originalException)
        {
            if (!condition)
            {
                __ContractsRuntime.ReportFailure(ContractFailureKind.PostconditionOnException, msg, conditionTxt, originalException);
            }
        }
    }
}
